[build]
publish = "."
functions = "netlify/functions"

[[redirects]]
from = "/chat"
to = "/.netlify/functions/server/chat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
