[build]
  publish = "."
  functions = "netlify/functions"

[functions."*"]
  timeout = 25

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
